### ISSUE TITLE
Guide on Localnet testing using Amman

### ISSUE THREAD

**Issue by anoushk1234** [Unboxed-Software/solana-course#126]
Localnet testing speeds up development quite a bit but certain programs are hard to test locally because they use other program deployed on mainnet or devnet like Metaplex's candy machine.

Using Amman we can teach people how to deploy a copy of these program locally so they can test these out on localnet.

**Comment by anoushk1234** [comment]
@jamesrp13 can i add this in the localnet testing section?

**Comment by jamesrp13** [comment]
@anoushk1234 that sounds pretty cool. Can you link me to something that gives me an idea of what you're wanting to add so I can think through how well it would fit?

**Comment by anoushk1234** [comment]
> @anoushk1234 that sounds pretty cool. Can you link me to something that gives me an idea of what you're wanting to add so I can think through how well it would fit?

The Metaplex js sdk repo uses amman, heres the config file for that https://github.com/metaplex-foundation/js/blob/main/.ammanrc.js

**Comment by jamesrp13** [comment]
@anoushk1234 if you're up for it I'd love to see a draft of what you're thinking and then decide if it fits in that lesson or if it should be some kind of side lesson that we can point to. Definitely something we can use, just want to make sure it ends up in the place that makes the most sense. Thanks!

**Comment by anoushk1234** [comment]
> @anoushk1234 if you're up for it I'd love to see a draft of what you're thinking and then decide if it fits in that lesson or if it should be some kind of side lesson that we can point to. Definitely something we can use, just want to make sure it ends up in the place that makes the most sense. Thanks!

hey @jamesrp13 already made a draft pr :) #145

**Comment by mikemaccana** [comment]
Draft PR never got update, it's been a while, and https://github.com/metaplex-foundation/amman seems dead now - closing the ticket.
