### ISSUE TITLE
Minting Solana NFTs using Rust

### ISSUE THREAD

**Issue by anoushk1234** [Unboxed-Software/solana-course#127]
There's already a guide on minting NFTs using candy machine in TS but what if I want to mint NFTs using my program and want to add some custom logic for these NFTs. I will need to make my own anchor program to mint these NFTs,

**Comment by hydrogenbond007** [comment]
True, buildspace made a great walkthrough build and there is also one on h[ere](https://openquest.xyz/quest/create_a_candy_machine_minting_nft_and_minting_website_v2).

**Comment by mikemaccana** [comment]
Hi @anoushk1234 and @hydrogenbond007 - the courses have now been migrated to https://solana.com/developers/courses and https://github.com/solana-foundation/developer-content/tree/main/content/courses. If you want to contribute a Rust NFT guide please add one!
