### ISSUE TITLE
Starter Codes are already completed

### ISSUE THREAD

**Issue by paarugsethi** [Unboxed-Software/solana-course#135]
The starter codes mentioned in the course already have the code that is explained in the chapters.

In order to practice and follow the chapter further, I had to first clean up the files that were already created in the repository and then make them again.

Examples here:
[Link Provided here.](https://github.com/Unboxed-Software/solana-ping-frontend/tree/starter)
<img width="916" alt="Screenshot 2022-08-18 at 1 13 55 PM" src="https://user-images.githubusercontent.com/87030959/185339261-2c6cefca-02eb-4489-adec-74d47b94dd7c.png">

**Comment by paarugsethi** [comment]
Pretty sure this is the problem here - https://github.com/Unboxed-Software/solana-course/issues/38

**Comment by mikemaccana** [comment]
Thanks @paarugsethi ! https://github.com/Unboxed-Software/solana-course/issues/38 seems to cover it, so I'll use that issue to fix this.
