### ISSUE TITLE
Adding Proof-of-Completion at the end of each chapter

### ISSUE THREAD

**Issue by paarugsethi** [Unboxed-Software/solana-course#138]
Would be good to have a section to attach a screenshot/GitHub Repo Link of the challenge or demo of that particular chapter in order to move to the next one instead of just ticking off the chapter manually. This would create accountability and ensure the completion of the challenges in the process of learning.

**Comment by hydrogenbond007** [comment]
yup, like the way Buildspace asks for a screenshot of the terminal at the end of every page

**Comment by mikemaccana** [comment]
This is a good idea, we've added a link to a feedback form that asks people to submit a github repo with their code at the end of each course.
