### ISSUE TITLE
Adding initial conext to the course, modules and each chapter

### ISSUE THREAD

**Issue by paarugsethi** [Unboxed-Software/solana-course#141]
An initial preface to the course, modules and each chapter (TLDR does solve it to an extent) would be great to provide some context on what folks are learning. This would ideally look like:

- An Introductory video and summary of the course at the start in the table of content
- Similar video and written introduction at the start of each module
- A small video walkthrough of each chapter and what folks are about to learn

**Comment by mikemaccana** [comment]
Hey Paruug! We'll be producing video versions of each chapter in the next couple of months. We'll handle that outside this course though.
