### ISSUE TITLE
Idea: A voluntary challenge/test at the end of each module

### ISSUE THREAD

**Issue by paarugsethi** [Unboxed-Software/solana-course#142]
While going from one module to another, a small challenge related to the topic of the module would be a great addition to recapping everything learnt in the chapters. Doesn't need to be compulsory to complete though since experienced folks might just want to skip it.

**Comment by mikemaccana** [comment]
@jamesrp13 and @CoachChuckFF have already been doing these (thanks gents). If you have more challenges please send PRs, but going to close this for now.
