### ISSUE TITLE
Token chapter: add more images

### ISSUE THREAD

**Issue by melodyserra** [Unboxed-Software/solana-course#151]
<img width="322" alt="Screen Shot 2022-09-01 at 2 35 27 PM" src="https://user-images.githubusercontent.com/6015339/190247476-9437198d-a5ac-4958-94e0-168c94a8ff4d.png">

**Comment by mikemaccana** [comment]
Thanks for filing this @melodyserra ! This content was moved to https://solana.com/developers/courses/tokens-and-nfts/token-program and the single, giant script reduced to smaller, more digestable steps. The current content now shows the expected output of each step too (as text, but we refer text for script output!).
