### ISSUE TITLE
Module 3.4 - Create a Basic Program, Part 3 - Basic Security and Validation - typo/inconsistency in description

### ISSUE THREAD

**Issue by podgostar** [Unboxed-Software/solana-course#168]
The section describing **Ownership checks** mentions that the note-taking app is the focus. However, in the next section, the first sentence talks about movie review apps. See directly cited text from module description below - inconsistency in italic/bold text: 

> **Ownership checks**
An ownership check verifies that an account is owned by the expected public key.  _**Let's use the note-taking app example**_ that we've referenced in previous lessons. In this app, users can create, update, and delete notes that are stored by the program in PDA accounts. 
>When a user invokes the update instruction, they also provide a pda_account. We presume the provided pda_account **_is for the particular movie review they want to update_**, but the user can input any instruction data they want. They could even potentially send data which matches the data format of a note account but was not also created by the note-taking program. This security vulnerability is one potential way to introduce malicious code.

**Comment by mikemaccana** [comment]
Thanks (and sorry about the wait). I just checked https://solana.com/developers/courses/native-onchain-development/program-security#ownership-checks (where this content now lives) and it's not updated to use the note taking program consistently.

> An ownership check verifies that an account is owned by the expected public key. Let's use the **note-taking app** example that we've referenced in previous lessons. In this app, users can create, update, and delete notes that are stored by the program in PDA accounts.

> When a user invokes the update instruction, they also provide a pda_account. We presume the provided pda_account is for the particular **note** they want to update, but the user can input any instruction data they want. They could even potentially send data which matches the data format of a note account but was not also created by the note-taking program. This security vulnerability is one potential way to introduce malicious code.
