### ISSUE TITLE
Minor Typo in Module 2 - 1.

### ISSUE THREAD

**Issue by Gator-RR** [Unboxed-Software/solana-course#186]
In Section "Token Account"  the first sentence says:
"Before you can mint tokens (issue new supply), you need a Token Account to hold the newly **issues** tokens."

I assume it should be

"Before you can mint tokens (issue new supply), you need a Token Account to hold the newly **issued** tokens."

**Comment by mikemaccana** [comment]
Thanks @Gator-RR !
