### ISSUE TITLE
Module 1.2: Dotenv can't be found, dotenv can

### ISSUE THREAD

**Issue by ovu-github** [Unboxed-Software/solana-course#21]
I'm doing Module 1.2 and there's a code snippet that requires importing Dotenv.
For some reason it doesn't work for me until the capital D is replaced by lowercase d.

```
import web3 = require('@solana/web3.js')
import Dotenv from 'Dotenv'
Dotenv.config()
```

**Comment by Gator-RR** [comment]
#26
