### ISSUE TITLE
Markdown backticks not rendering on soldev.app

### ISSUE THREAD

**Issue by mikemaccana** [Unboxed-Software/solana-course#213]
Markdown backticks are not rendering on soldev.app. From https://github.com/Unboxed-Software/solana-course/blob/main/content/hello-world-program.md:

```
The path to a particular module or item is the name of each step from the crate to that module where each is separated by `::`. As an example, let's look at the following structure:

1. The base crate is `solana_program`
2. `solana_program` contains a module named `account_info`
3. `account_info` contains a struct named `AccountInfo`

The path to `AccountInfo` would be `solana_program::account_info::AccountInfo`.
```

Is rendered ignoring backticks, eg from https://www.soldev.app/course/hello-world-program: 

<img width="916" alt="Screenshot 2023-07-11 at 16 21 38" src="https://github.com/Unboxed-Software/solana-course/assets/172594/b6f3dabf-2ba5-474a-bc37-8dfbb99651b3">

It should look like:

<img width="1125" alt="Screenshot 2023-07-11 at 16 23 48" src="https://github.com/Unboxed-Software/solana-course/assets/172594/6fc8f5a7-50f1-458c-821c-77b078285c41">

## The fix

It looks like the `.inline-code` class is missing a `font-family` declaration. Would fix this myself but there's [no info about how the course in rendered in the README](https://github.com/Unboxed-Software/solana-course) and I can't find info on how the rendered version is built.

**Comment by mikemaccana** [comment]
Tagging @jamesrp13 per `CONTRIBUTING.md`.

**Comment by mikemaccana** [comment]
wherever the code lives:

```
span.inline-code {
    border-radius: 3px;
    padding: 3px;
    font-family: monospace;
    background: #dddddd;
}
```

Should fix it. 
<img width="975" alt="Screenshot 2023-07-14 at 17 11 02" src="https://github.com/Unboxed-Software/solana-course/assets/172594/30967f7a-f6a6-457b-99b1-54a33af7c24b">

**Comment by jamesrp13** [comment]
@mikemaccana sorry for the delay in responding. The soldev site is actually owned and maintained by a different organization (Ironforge). That being said, it's open source and I'm sure they'd appreciate a PR with these changes. The repo is [here](https://github.com/ironforge-cloud/soldev-ui). Let me know if you can't get around to it and I'll make sure to send a message to them to get this on their radar.
