### ISSUE TITLE
Miss-information about data ordering ...

### ISSUE THREAD

**Issue by pooriagg** [Unboxed-Software/solana-course#239]
Hello, dear soldev team. i think there is a mistake in section "Data Order" FROM "Dealing with Accounts" subject, that you say you must always place the dynamic variables like Vectors and strings in the end of the Account's data structure to be able to keep track of static variables like ids very easy BUT it really does not matter how to order them for example:

![272323300-46814bd0-0f3c-4df7-b5f8-af753a65cddc](https://github.com/Unboxed-Software/solana-course/assets/104061307/ce34ec34-6104-44d7-ab07-aba29e4a4c5b)

#[account]
pub struct Data {
scores: Vec,
id: u8
}

- In the top example you must specify a static space for your vector, in the account creation time it looks like it is dynamic but in Solana under the hood it is static beacuz the blockchain's space is limited and we have exatcly specify how mush space we want to rent.
Raw data output for Data's PDA account (with considering10 elements in the vector) :

- <Buffer ce 9c 3b bc 12 4f f0 e8 03 00 00 00 0a 05 ff 00 00 00 00 00 00 00 01>
discriminator(8 bytes) + vector-u8(4 + (10 * 1)) + id-u8(1 byte)

- Memcmp for tracking the "id" section:
{
offset: 8 + 14,
bytes: base58.encode(id)
}

@jamesrp13

**Comment by jamesrp13** [comment]
You don't *have* to, but it simplifies things significantly. I can look into rewording, but your assertion that it doesn't matter is incorrect. You can absolutely have a dynamic size vector (I do it often) inside an account. Even with a statically sized account the vector itself doesn't have to be static, it can start small and leave empty bytes in the account and then grow and shrink over time. But you can also reallocate accounts to change size over time. We've experienced the pain of putting statically sized fields after dynamic fields repeatedly and feel 100% confident it's worth calling out.

**Comment by pooriagg** [comment]
Yes i know, i myself always declare dynamic variables after static variables it is awesome approach BUT the description itself is not true.

**Comment by jamesrp13** [comment]
Got it. Would you mind quoting the portion you think is not true so I can know exactly where to look?

**Comment by pooriagg** [comment]
As i said before an accounts has an static space for example 20 bytes and it no matters you have stored static or dynamic sized variables there, account has always a static Buffer<20 bytes> unless you reallocate a new space to it.

**Comment by pooriagg** [comment]
![Screenshot 2023-10-06 163227](https://github.com/Unboxed-Software/solana-course/assets/104061307/3a46ce95-1733-42c2-967c-ac4fc97c45d2)

**Comment by jamesrp13** [comment]
I still don't understand what you're pointing out as misinformation. Please submit a PR with the changes you think should be made and we can discuss there.
