### ISSUE TITLE
problems module 4 lesson 2

### ISSUE THREAD

**Issue by sebatustra** [Unboxed-Software/solana-course#245]
Hey hey I am having issues interacting with the solana programs deployed to devnet with the provided frontends...
I have basically cloned both the solana program and frontend, and i am in the correct branches, changed only program id in the front.
I get the following error with Phantom wallet when creating a review:

Error processing instruction 2
{"code":-32002}

Solfrare is a bit more precise:
{"error":{"logs":["Program AqquXG7sx7JUpycVdQLRGue6imkyYtw8U9w4ZzcDj2gi invoke [1]","Program log: process_instruction: AqquXG7sx7JUpycVdQLRGue6imkyYtw8U9w4ZzcDj2gi: 4 accounts, data=[0, 4, 0, 0, 0, 115, 100, 115, 100, 2, 6, 0, 0, 0, 97, 115, 100, 97, 115, 100]","Program log: Adding movie review...","Program log: Title: sdsd","Program log: Rating: 2","Program log: Description: asdasd","Program AqquXG7sx7JUpycVdQLRGue6imkyYtw8U9w4ZzcDj2gi consumed 25151 of 200000 compute units","Program AqquXG7sx7JUpycVdQLRGue6imkyYtw8U9w4ZzcDj2gi failed: Instruction passed to inner instruction is too large (12884933430 > 1280)"]},"name":"WalletSendTransactionError"}

Please fix it i am enjoying the course so much but it is frustrating to not be able to test my programs!

**Comment by mikemaccana** [comment]
Thanks for letting us know about this. This content has now moved to [solana.com](https://solana.com/developers/courses), and we're about to hire someone to check every course and fix potential issues like this. Thanks for letting us know though!
