### ISSUE TITLE
‘Sort’ in M1 Class 7

### ISSUE THREAD

**Issue by brunofrota8** [Unboxed-Software/solana-course#248]
In M1 Class 7 the ‘Sort’ function isn’t working anymore. I really don’t know why, but it’s seems that getProgramAccount don’t have this command anymore.

I tried to download the source code from git, deleted the package.lock and run ‘npm i install’ and didn’t work too

**Comment by brunofrota8** [comment]
This is my first time creating a issue, so sorry if I did any mistake

**Comment by mikemaccana** [comment]
Hi @brunofrota8 ! Thanks for filing this. We're about to hire someone to go through the whole course and fix these issues, so I'm closing this.
