### ISSUE TITLE
Question about Note Taking exercise

### ISSUE THREAD

**Issue by nasadorian** [Unboxed-Software/solana-course#250]
Hi! I’m working through the course and had a question about how PDAs are supposed to work in the note taking example. I couldn’t find a reference implementation. Please see below:

https://solana.stackexchange.com/questions/8049/note-taking-example-from-solana-dev-course

**Comment by mikemaccana** [comment]
I think this is fairly well answered by the Stack Exchange answer - please do let us know (or better yet send a PR) if there's something we could do better in the note taking chapter though!
