### ISSUE TITLE
Portuguese support

### ISSUE THREAD

**Issue by canokaue** [Unboxed-Software/solana-course#256]
heeey @jamesrp13 & folks, I'd like to offer help on translating https://www.soldev.app/course to Portuguese.

should I just adhere to the current content/es-like structure (content/pt), committing it to the draft branch?

I'm thinking about submitting just the texts translations first, due this December, and later on think about translating assets, if that's ok.

let me know your thoughts, have a great week

**Comment by jamesrp13** [comment]
That would be great! Thanks for jumping in.

What you said will work out great - just adhere to the same structure and lmk if you have any questions. If anything about the structure changes I'll try to remember to let you know, but please keep an eye on commit history to be safe. Thanks!

**Comment by brunofrota8** [comment]
Hi @canokaue I am doing the course step-by-step ping me if you need any help. We can share some drive before commit.

**Comment by mikemaccana** [comment]
Thanks @canokaue ! This content has now moved to [solana.com](https://solana.com/developers/courses), and we have a paid translation service, but your contribution is much appreciated1
