### ISSUE TITLE
Second course fails with "bigint: Failed to load bindings, pure JS will be used"

### ISSUE THREAD

**Issue by adaptive-adam** [Unboxed-Software/solana-course#27]
When I try to run the course https://github.com/Unboxed-Software/solana-course/blob/main/content/intro-to-writing-data.md I get the following error.
Platform Mac Air,  Apple silicon

```
bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)
```

**Comment by jamesrp13** [comment]
@adaptive-adam not sure I understand exactly what problem you're referring to. The file you've referenced is simply a markdown file meant to be viewed directly in GitHub or in another markdown previewer that you prefer. You shouldn't need to run or build anything.

**Comment by metasal1** [comment]
BigInt issue is resolved when you update to the latest SolanaWeb3.js

**Comment by mikemaccana** [comment]
Closing this as it sounds like it's resolved. Please reopen if not.
