### ISSUE TITLE
Fixes needed to intro-to-custom-on-chain-programs

### ISSUE THREAD

**Issue by adlonymous** [Unboxed-Software/solana-course#283]
Section 1. Basic Scaffolding of Lab

The first line import is:
import { Keypair } from "@solana/web3.js";

instead of:
import * as web3 from "@solana/web3.js";

The lab code is also missing the function call for sendPingTransaction:
sendPingTransaction(connection, payer);
after the function is declared and written

**Comment by mikemaccana** [comment]
Thanks! Not to self this is is `intro-to-custom-on-chain-programs.md` fixing on Tuesday.
