### ISSUE TITLE
Typo in 'Asymmetric Cryptography' ul li item

### ISSUE THREAD

**Issue by triangletrianglesquareplusx** [Unboxed-Software/solana-course#284]
Within the Asymmetric Cryptography list in the [1] Cryptography Fundamentals section there is a typo when providing examples of algorithms. 

ECC and RSA are Asymmetric, not symmetric. 
![asymmetric](https://github.com/Unboxed-Software/solana-course/assets/69000271/6da3032c-8396-4a98-965b-72569c929c67)

**Comment by bunnyBites** [comment]
Yeah, I noticed this one. I have raised a PR for this and also minor other typos found on the page. Here check this out:
https://github.com/Unboxed-Software/solana-course/pull/285

**Comment by triangletrianglesquareplusx** [comment]
Ah, sorry then, will close.
