### ISSUE TITLE
Dark mode for Solana Course documentation

### ISSUE THREAD

**Issue by bunnyBites** [Unboxed-Software/solana-course#286]
I think the documentation page looks better with a dark mode enabled. I also noticed a dark mode available in Solana documentation, but it needed to be provided in the Solana Development course section.

I would like to contribute to this feature. Let me know what you think @jamesrp13.

**Comment by jamesrp13** [comment]
It sounds like you're talking about frontend changes, but this org doesn't own the frontend hosting the course. You'd have to contribute directly to soldev.

**Comment by bunnyBites** [comment]
Sure, I'll hop there and have a look. Thanks☺️

**Comment by mikemaccana** [comment]
Hey @bunnyBites we already have people working on this! Thanks for the offer of help but this should be out shortly.
