### ISSUE TITLE
Add Chinese Translation

### ISSUE THREAD

**Issue by longxiaoLX** [Unboxed-Software/solana-course#295]
These documents have helped me a lot in learning Solana.  I want to add Chinese translation content to share it with more Chinese people. When the plan is agreed upon, I plan to spend a month completing it. Please check. @jamesrp13

**Comment by jamesrp13** [comment]
Awesome! So glad the course has been helpful for you. @mikemaccana do you know if anyone is already working on a Chinese translation?

**Comment by longxiaoLX** [comment]
Hi, @jamesrp13 @mikemaccana . What is the situation now?

**Comment by mikemaccana** [comment]
Hi there @longxiaoLX ! No, there's not anyone currently working on a Chinese translation. We'd love for you to create one!

**Comment by yjshi2015** [comment]
Great, I might join ~

**Comment by longxiaoLX** [comment]
Hi, @mikemaccana . I have created a new [PR](https://github.com/Unboxed-Software/solana-course/pull/298) . Please leave your contact information @yjshi2015 , and we can work together.

**Comment by yjshi2015** [comment]
Hi, @mikemaccana . we have started translation🚀🚀🚀. It would be best if you create a new branch so that everyone can contribute to the translation, Thx~

**Comment by mikemaccana** [comment]
Thanks! I've merged.
