### ISSUE TITLE
the client-side script in "local-setup chapter" of Intermediate Solana Program Development need to be adjusted

### ISSUE THREAD

**Issue by yjshi2015** [Unboxed-Software/solana-course#303]
[The article](https://www.soldev.app/course/local-setup#:~:text=side%20script.-,Replace,-the%20program%20ID) mentioned that `program_id` needs to be modified, and the following may also need to be adjusted:

**1. cluster URL**

`let connection = new web3.Connection(web3.clusterApiUrl("devnet"))` -> `const connection = new web3.Connection('http://localhost:8899')`

**2. Transaction signature URL**

console.log(`Transaction: https://explorer.solana.com/tx/${transactionSignature}?cluster=devnet`) 
To 
console.log(`Transaction: https://explorer.solana.com/tx/$ {transactionSignature}?cluster=custom`)

**_Note_**：the transactionSignature url will be invalid soon, because the localhost node loads a smaller snapshot of historical data.

**Comment by mikemaccana** [comment]
Moved to new repo - thanks for reporting, I'll check this in a sec.
