### ISSUE TITLE
Updated Phantom wallet instructions in interact-with-wallets

### ISSUE THREAD

**Issue by bqmackay** [Unboxed-Software/solana-course#309]
Phantom Wallet has changed its UI, and the instructions to use Devnet through the app have changed. The instructions are now:

1. Open the Phantom Extension's UI
2. Open settings by clicking on the Menu > Cog
3. Open Developer Settings and click on the Testnet Mode toggle (Devnet should be selected by default)

These instructions would modify the following:

Once you have a wallet, click the settings gear on the bottom right in the Phantom UI. Scroll down and click on the line item “Change Network” and select “Devnet.” This ensures that Phantom will be connected to the same network we’ll be using in this lab.

**Comment by mikemaccana** [comment]
Hi @bqmackay thanks for spotting this! Can you please send a PR to make these changes?

**Comment by mikemaccana** [comment]
Thanks @bqmackay ! This content is now on https://solana.com/developers/courses/intro-to-solana/interact-with-wallets#download-a-solana-wallet and we have instructions for Phantom, Solflare and Backpack.
