### ISSUE TITLE
Support links opening in new tabs

### ISSUE THREAD

**Issue by bqmackay** [Unboxed-Software/solana-course#310]
Most links in the material open in the same browser tab as the reading. This causes a problem if I need to reference the reading because I must hit back instead of just switching tabs. A better user experience would be to have links open a new tab so I can quickly switch between the two.

**Comment by jinali98** [comment]
Hello, is anyone working on this at the moment? if not I would like to work on this

**Comment by mikemaccana** [comment]
The course will be moving to solana.com this week, which already handles opening links offsite in new tabs. We can reopen if there's anything else we need but we should be good to go here.
