### ISSUE TITLE
Updated walkthrough code examples to match the solution repo in interact-with-wallets

### ISSUE THREAD

**Issue by bqmackay** [Unboxed-Software/solana-course#311]
In the lab section of the Interact with Wallets page, the WalletContextProvider code uses the `useMemo` function to get wallets, but the solution code correctly uses `walletAdapterWallets`.

Here's the broken code from the lab:

```
#...imports...

const Home: NextPage = (props) => {
  const endpoint = web3.clusterApiUrl("devnet");
  const wallets = useMemo(() => [], []); # <===== useMemo is here, but not imported from React
```

And here's the correct line from the solution repo:
```
const wallets = [new walletAdapterWallets.PhantomWalletAdapter()];
```

**Comment by mikemaccana** [comment]
Thanks @bqmackay - the courses have now been migrated to https://solana.com/developers/courses and https://github.com/solana-foundation/developer-content/tree/main/content/courses - can you please send a PR to that repo?

**Comment by mikemaccana** [comment]
Moved to new repo
