### ISSUE TITLE
French support

### ISSUE THREAD

**Issue by thomassimmer** [Unboxed-Software/solana-course#318]
Hello @jamesrp13, I would like to help translating https://www.soldev.app/course to French.

I did read the CONTRIBUTING.md file.

I can submit the texts translations first, during the next two months probably, and then translate assets later, if that's ok for you.

Let me know your thoughts.

Cheers.

**Comment by jamesrp13** [comment]
Hey @thomassimmer sorry for the delayed response!

I'm tagging @mikemaccana in case he knows of anyone working on French already. Either way, I'm sure we'd love your help! Just want to make sure you aren't duplicating effort on specific lessons.

**Comment by mikemaccana** [comment]
Hi @thomassimmer ! The courses have now been migrated to https://solana.com/developers/courses and https://github.com/solana-foundation/developer-content/tree/main/content/courses. We now have a paid service that does language translation - but thank you for the offer!
