### ISSUE TITLE
Fix intro-to-writing-data.md

### ISSUE THREAD

**Issue by thomassimmer** [Unboxed-Software/solana-course#319]
Hi,

I noticed a few mistakes in intro-to-writing-data.md.

I will propose a PR to fix them.

Cheers.

**Comment by olvr** [comment]
Looks like I missed this while posting my issue and it refers to the same problems https://github.com/Unboxed-Software/solana-course/issues/320

I specified the mistakes I found, so you might find that a helpful reference.

**Comment by mikemaccana** [comment]
Thanks @olvr we just noticed the same issues in #322. 

You've got some good stuff here though I'll fix the conflicts and merge.

**Comment by mikemaccana** [comment]
I checked out the PR but there were many things broken by the bad PR that needed more substantial fixes. See #322
