### ISSUE TITLE
Missing repo for the lab in rust-macros.md

### ISSUE THREAD

**Issue by thomassimmer** [Unboxed-Software/solana-course#329]
Hello,

I have got a 404 error on https://github.com/Unboxed-Software/anchor-custom-macro/tree/starter in lesson "Rust Procedural Macros".

It makes it complicated to understand this lab. The project may be private ?

Cheers,
Thomas

**Comment by mikemaccana** [comment]
This is back up: https://github.com/Unboxed-Software/anchor-custom-macro/tree/starter
