### ISSUE TITLE
I want to get a program-data address and upgrade-authority from a program account info in solana native program. how can i do it ? i have tried the UpgradableLoaderState but i didn't found any deseralizer or something like that .

### ISSUE THREAD

**Issue by pooriagg** [Unboxed-Software/solana-course#338]
I want to get a program-data address and upgrade-authority from a program account info in solana native program. how can i do it ? i have tried the UpgradableLoaderState but i didn't found any deseralizer or something like that .

**Comment by mikemaccana** [comment]
Hey there! Please use https://solana.stackexchange.com/ for questions like this.
