### ISSUE TITLE
Extends Versioned Transaction will not work without ComputeBudgetProgram.setComputeUnitLimit

### ISSUE THREAD

**Issue by 0xk2** [Unboxed-Software/solana-course#376]
In this article https://www.soldev.app/course/versioned-transaction

If I seperate the create & extend LUT instructions into 2 transactions then it always returns 'Computational Budget Exceed' in the extending transaction, [example](https://explorer.solana.com/tx/3pG4HDMwKwNv2VdKdRYBH1Ryaz3FBBwoLuTEo9JGV5u6SWcj6NfHp2ppNZzQfWKsxFWe4vdH5tjAS84JnGado4Ku?cluster=devne)
It seems that the client always miscalculate the required compute budget for extending LUT.
Solution is adding a `ComputeBudgetProgram.setComputeUnitLimit` instruction within the extending transaction, like [this](https://explorer.solana.com/tx/368MH7QrHX2vWaEHqmmFHoyEFbLmyNDraiyiG8stC2NtMVLK8cir33NschXbk2xr3uJvXeaPfmbmNqpXSx5eveVe?cluster=devnet)
The fixed code:
```
const extendLookupTableTxid = await sendV0Transaction(connection, user, [
  extendInstruction,
  ComputeBudgetProgram.setComputeUnitLimit({
    units: 200000,
  }),
]);
```

**Comment by mikemaccana** [comment]
Hi @0xk2 ! The soldev course has moved to solana.com. Can you please send a PR to the new repository? The code is at https://github.com/solana-foundation/developer-content/blob/main/content/courses/program-optimization/lookup-tables.md

**Comment by mikemaccana** [comment]
Closing as I've filed this in the other repo
