### ISSUE TITLE
Add reminder to check branch for starter/solution code

### ISSUE THREAD

**Issue by jamesrp13** [Unboxed-Software/solana-course#38]
Everywhere there's mention of starter code/solution code with a link, we should add a reminder that if the clone the repo they'll need to change the branch to the corresponding branch (e.g. starter if they want starter code, solution if they want solution code). The links go to the right branch, but if you clone it then your local repo will default to the main branch.

**Comment by mikemaccana** [comment]
Moved to issue in new repo!
