### ISSUE TITLE
unclear explanation of airDropIfRequired() on intro-to-writing-data.md

### ISSUE THREAD

**Issue by terryds** [Unboxed-Software/solana-course#380]
we need to add more info about the last argument of the function airdropIfRequired() to make it more clear for the readers because the current page has no explanation why the last argument of the function is 0.5 SOL

![image](https://github.com/Unboxed-Software/solana-course/assets/11571395/d10e6202-0b4a-4ac6-a80d-8a1c9a5ed906)

I will create a PR about this

**Comment by terryds** [comment]
PR Created: https://github.com/Unboxed-Software/solana-course/pull/381

**Comment by mikemaccana** [comment]
Good point and thanks for fixing @terryds !
