### ISSUE TITLE
Add balances to starter and solution of Token Swap demo

### ISSUE THREAD

**Issue by jamesrp13** [Unboxed-Software/solana-course#42]
Would be nice to show token balances for the tokens (krypt, scrooge, and lp). They don't have metadata so they don't show up easily viewable in Phantom.

https://github.com/Unboxed-Software/solana-token-swap-frontend

**Comment by mikemaccana** [comment]
Closing this, `solana-token-swap-frontend` isn't referenced in the current courses. Looks like it was removed at some point?
