### ISSUE TITLE
Add token metadata to tokens in the Token Program lesson

### ISSUE THREAD

**Issue by jamesrp13** [Unboxed-Software/solana-course#46]

**Comment by mikemaccana** [comment]
Ooh I needed to add this for the training program (same thing, I expected it to be there then realised it wasn't). 

One sec, I'll add it now...

**Comment by mikemaccana** [comment]
(also yes, we have Token Extensions, but Explorer still isn't ready and I do think it's reasonable to support Metaplex for a little while yet)
