### ISSUE TITLE
Extend clickable / linked area to the entire container

### ISSUE THREAD

**Issue by kquirapas** [Unboxed-Software/solana-course#86]
**Let me preface this by saying I love what you guys are doing and I'm up to help as much as I can. Grateful for the work you guys put in here**

For the course page:

Each section in the module is clickable but only when the text itself is clicked. The cursor changes into a pointer (the one for clicking links) and the container responds by becoming brighter but it's not reacting to the click unless I click directly on the text.

This might be nitpicking, but just wanted to let you guys know it happens.

Do you guys think it would be better to let the entire container clickable and linked to content?

**Comment by jamesrp13** [comment]
Is this on soldev.app? If so, that is a separate site maintained by another organization. I can find the repo and link you to it.

**Comment by kquirapas** [comment]
Ohh! No wonder I didn't find the UI code in. I thought you guys were using some kind of parser.

Thank you James! Cheers

**Comment by jamesrp13** [comment]
Found it I think https://github.com/metasoftware-labs/soldev-ui

If you wouldn't mind putting the issue in there that would be great!

**Comment by kquirapas** [comment]
Yes most definitely! Closing this now James. Thank you
