### ISSUE TITLE
Metaplex Changes

### ISSUE THREAD

**Issue by grantsheen** [Unboxed-Software/solana-course#95]
in the "Create Solana NFTs with Metaplex" section. on step 3 of the demo, it says to clone the Metaplex repository: https://github.com/metaplex-foundation/metaplex.git, but i think Metaplex deprecated the repository because it has turned into just a readme file.

**Comment by mikemaccana** [comment]
Just checked and https://www.soldev.app/course/nfts-with-metaplex doesn't mention cloning any repositories anymore.
